version: '3.7'

services:
  nginx:   
    image: nginx:1.23.1
    container_name: mediawiki-nginx
    ports:   
      - 8088:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www/html:/var/www/html
    depends_on:
      - php
    networks:
      - mynetwork

  php:
    image: alejandrogalera/php:7.4.30-fpm-alpine3.16
    build:
      dockerfile: Dockerfile
      context: ./php
    container_name: mediawiki-php
    volumes:
      - ./www/html:/var/www/html
    ports:
      - 9000:9000
    networks:
      - mynetwork

  mysql:
    image: mysql/mysql-server:8.0.30
    container_name: mediawiki-db
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: <fixme> 
    #  MYSQL_DATABASE: mediawikidb
    #  MYSQL_USER: mediawikiuser
    #  MYSQL_PASSWORD: password
    networks:
      - mynetwork

networks:
  mynetwork:
    
